# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Configuration des sessions
    session:
        name: 'Authentification'
        cookie_secure: false
        cookie_httponly: true
        cookie_lifetime: 3600
        gc_maxlifetime: 3600
    csrf_protection: true
    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
