# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

client_info:
  path: /client/info/{nom}
  controller: App\Controller\ClientController2::info
  
client_photo:
  path: /client/photo/{nom}
  controller: App\Controller\ClientController2::photo

client_prenom:
  path: /client/prenom/{parametre}
  requirements: 
    url : '[a-z]+(-[a-z]+)*'
  controller: App\Controller\ClientController2::prenom

controllers:
    resource: ../src/Controller/
    type: attribute
